name: Dependabot auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  review-dependabot-pr:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable conditional auto merge
        if: |
          startsWith(${{ steps.dependabot-metadata.outputs.update-type }}, 'version-update:semver-) &&
          startsWith(${{ steps.dependabot-metadata.outputs.dependency-type }}, 'direct:)
        uses: grahamalama/dependabot-automerge@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          dependency-type: ${{ steps.dependabot-metadata.outputs.dependency-type }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          label: "needs-qa"
          merge-strategy: "squash"
          prod-dep-semver-autoapprove: "patch"
          semver-level: ${{ steps.dependabot-metadata.outputs.update-type }}
